---
# .github/workflows/ci.yml

name: CI

"on":
  - push
  - pull_request

env:
  THESEUS_LOAD_DOTENV: false

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            constraints.txt

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dev deps
        run: |
          pip install -c constraints.txt -e .[dev]

      - name: Lint Python
        run: flake8 src tests

      - name: Lint YAML
        run: yamllint .

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            constraints.txt

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install test deps
        run: pip install -c constraints.txt -e .[test]

      - name: CI pytest Discovery Sanity Review
        run: |
          echo "(cmd) pytest -q --collect-only:"
          pytest -q --collect-only

      - name: Run tests
        run: |
          pytest --maxfail=4 --disable-warnings -q
